# Generated by Django 3.2.7 on 2021-09-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinstance',
            old_name='registration',
            new_name='car',
        ),
    ]
