# Generated by Django 3.2.7 on 2021-09-30 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0003_alter_car_car_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='carlisting.carmake'),
        ),
    ]
