# Generated by Django 3.2.7 on 2021-09-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0004_alter_car_car_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
