# Generated by Django 3.2.7 on 2021-10-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0007_alter_car_car_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carinstance',
            options={'ordering': ['due_back']},
        ),
    ]
